<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MonthJanuaryFebruaryMarchAprilMayJun_aa9ebb</name>
   <tag></tag>
   <elementGuidId>7f9dd9dc-0697-4871-a871-154f62be662f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/article/div/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/div[5]/div/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-select bg-white focus:outline-none h-14 py-4 px-5 text-base border focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MonthJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;w-full flex-grow flex-shrink absolute top-20 left-0 right-0 bottom-0 lg:pl-20 xxl:pl-64 z-0&quot;]/article[@class=&quot;w-full h-full flex flex-col overflow-hidden&quot;]/div[@class=&quot;h-full overflow-y-auto&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col sm:flex-row m-4 sm:mx-6 sm:-mt-10 sm:z-10 text-white sm:space-x-6&quot;]/div[@class=&quot;absolute sm:relative sm:rounded-lg h-full w-full inset-0 z-20 bg-pop-gray-100&quot;]/div[@class=&quot;route-card flex flex-col bg-white rounded-lg py-6 px-4 sm:p-6 m-4 sm:m-0 box-border shadow-sm&quot;]/div[@class=&quot;flex flex-col w-full mt-10 space-y-10&quot;]/div[@class=&quot;flex flex-col lg:grid grid-cols-2 gap-2 sm:gap-6 lg:gap-10 my-10 sm:my-0 text-pop-gray space-y-4 sm:space-y-0&quot;]/div[@class=&quot;flex flex-col col-span-2&quot;]/div[@class=&quot;date-select&quot;]/div[@class=&quot;input-select-wrapper mt-0 mb-2 month cursor-pointer&quot;]/div[@class=&quot;relative&quot;]/select[@class=&quot;input-select bg-white focus:outline-none h-14 py-4 px-5 text-base border focus:ring-pop-orange focus:border-pop-orange border-pop-gray-200&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/article/div/div/div/div[2]/div[2]/div[2]/div[3]/div[2]/div[5]/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
